#!/bin/bash

SOURCE_DIR=../bitdust.docs

for mdfilepath in $SOURCE_DIR/*.md
do
    mdfile=$(basename "$mdfilepath")
    htmlfile="${mdfile/.md/.html}"
    python md2html.py "$SOURCE_DIR/$mdfile" > "./wiki/$htmlfile"
    python fix_html.py "./wiki/$htmlfile" "./wiki/$htmlfile"
    echo "$SOURCE_DIR/$mdfile -> ./wiki/$htmlfile"
done
