#!/bin/bash

# ./buildone settings.md

SOURCE_DIR=../bitdust.docs
mdfilepath=$SOURCE_DIR/$1
mdfile=$(basename "$mdfilepath")
htmlfile="${mdfile/.md/.html}"
python md2html.py "$SOURCE_DIR/$mdfile" > "./wiki/$htmlfile"
python fix_html.py "./wiki/$htmlfile" "./wiki/$htmlfile"
echo "$SOURCE_DIR/$mdfile -> ./wiki/$htmlfile"


