#!/bin/bash
#
# As a preparation, a few other BitDust repositories need to be already prepared inside your home folder:
#
#     cd ~
#     git clone https://github.com/bitdust-io/public bitdust
#     git clone https://github.com/bitdust-io/states bitdust.states
#     git clone https://github.com/bitdust-io/docs.git bitdust.docs
#     git clone https://github.com/bitdust-io/www.git bitdust.www
#
# Then you run the script to rebuild the web site files in-place:
#
#     cd bitdust.www
#     ./deploy
#


cd ~/bitdust/
git pull


cd ~/bitdust.docs/
git fetch --all
git reset --hard origin/master
python build_api.py ../bitdust/bitdust/interface/api.py api.md
python build_settings.py ../bitdust/ settings.md
python build_changelog.py ../bitdust/CHANGELOG.txt changelog.md


cd ~/bitdust.states/
git fetch --all
git reset --hard origin/master


cd ~/bitdust.www/
git fetch --all
git reset --hard origin/master
./build
./build_visual


echo "DONE!"
