#!/bin/bash
#
# As a preparation, a few other BitDust repositories need to be already prepared inside your home folder:
#
#     cd ~
#     git clone https://github.com/bitdust-io/public bitdust
#     git clone https://github.com/bitdust-io/states bitdust.states
#     git clone https://github.com/bitdust-io/docs.git bitdust.docs
#     git clone https://github.com/bitdust-io/www.git bitdust.www
#
# Then you run the script to rebuild the web site files in-place:
#
#     cd bitdust.www
#     ./deploy
#

python3 -m pip install markdown2


cd ~/bitdust/
git fetch --all
git reset --hard origin/master


cd ~/bitdust.docs/
git fetch --all
git reset --hard origin/master
python3 build_api.py ../bitdust/bitdust/interface/api.py api.md
python3 build_settings.py ../bitdust/ settings.md
python3 build_changelog.py ../bitdust/CHANGELOG.txt changelog.md


cd ~/bitdust.states/
git fetch --all
git reset --hard origin/master


cd ~/bitdust.www/
git fetch --all
git reset --hard origin/master
./build_visual
./build


cd ~
rm -rf www
mkdir www
cp -v -r ~/bitdust.www/wiki ~/www/
cp -v -r ~/bitdust.www/pics ~/www/
cp -v -r ~/bitdust.www/logos ~/www/
cp -v -r ~/bitdust.www/js ~/www/
cp -v -r ~/bitdust.www/images ~/www/
cp -v -r ~/bitdust.www/fonts ~/www/
cp -v -r ~/bitdust.www/css ~/www/
cp -v -r ~/bitdust.www/images ~/www/
cp -v -r ~/bitdust.www/assets ~/www/
cp -v ~/bitdust.www/*.html ~/www/
cp -v ~/bitdust.www/*.xml ~/www/
cp -v ~/bitdust.www/*.webmanifest ~/www/
cp -v ~/bitdust.www/*.css ~/www/
cp -v ~/bitdust.www/*.js ~/www/
cp -v ~/bitdust.www/*.txt ~/www/

echo "DONE!"
